server:
  port: 8080

spring:
  profiles:
    active: Maxx
  datasource:
      url: jdbc:mariadb://localhost:3306/resume_dbb  # Здесь url для MariaDB
      username: Maxx
      password: "вгвгыреу"
      driver-class-name: org.mariadb.jdbc.Driver  # Драйвер для MariaDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect